# https://docs.codecov.io/docs/common-recipe-list
# https://docs.codecov.io/docs/commit-status#patch-status

coverage:
  status:

    project:
      default:
        target: auto    # the required coverage value
        threshold: 3%   # the leniency in hitting the target

    patch:
      default:
        informational: true
