---
name: release

on: push

permissions:
  contents: read
  checks: write
  statuses: write

jobs:
  pypi:
    name: 'Build & publish package to PyPI'
    runs-on: 'ubuntu-latest'
    steps:

      - name: Acquire source code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          activate-environment: true
          enable-cache: true
          python-version: "3.14"

      - name: Install Hatch
        uses: pypa/hatch@install

      - name: Install Twine
        run: uv pip install twine

      - name: Build package
        run: hatch build

      - name: Validate package
        run: twine check dist/*

      - name: Publish package to PyPI
        if: startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
